export default {
  'align-content': [
    'stretch',
    'center',
    'flex-start',
    'flex-end',
    'space-between',
    'space-around',
    'initial',
    'inherit',
  ],
  'align-items': ['stretch', 'center', 'flex-start', 'flex-end', 'baseline', 'initial', 'inherit'],
  'align-self': [
    'auto',
    'stretch',
    'center',
    'flex-start',
    'flex-end',
    'baseline',
    'initial',
    'inherit',
  ],
  all: ['initial', 'inherit', 'unset'],
  animation: ['initial', 'inherit'],
  'animation-delay': ['initial', 'inherit'],
  'animation-direction': [
    'normal',
    'reverse',
    'alternate',
    'alternate-reverse',
    'initial',
    'inherit',
  ],
  'animation-duration': ['initial', 'inherit'],
  'animation-fill-mode': ['none', 'forwards', 'backwards', 'both', 'initial', 'inherit'],
  'animation-iteration-count': ['infinite', 'initial', 'inherit'],
  'animation-name': ['none', 'initial', 'inherit'],
  'animation-play-state': ['paused', 'running', 'initial', 'inherit'],
  'animation-timing-function': [
    'linear',
    'ease',
    'ease-in',
    'ease-out',
    'ease-in-out',
    'step-start',
    'step-end',
    'cubic-bezier',
    'initial',
    'inherit',
  ],
  'backface-visibility': ['visible', 'hidden', 'initial', 'inherit'],
  background: ['initial', 'inherit'],
  'background-attachment': ['scroll', 'fixed', 'local', 'initial', 'inherit'],
  'background-blend-mode': [
    'normal',
    'multiply',
    'screen',
    'overlay',
    'darken',
    'lighten',
    'color-dodge',
    'saturation',
    'luminosity',
  ],
  'background-clip': ['border-box', 'padding-box', 'content-box', 'initial', 'inherit'],
  'background-color': ['transparent', 'initial', 'inherit'],
  'background-image': ['none', 'initial', 'inherit'],
  'background-origin': ['padding-box', 'border-box', 'content-box', 'initial', 'inherit'],
  'background-position': [
    'left top',
    'left center',
    'left bottom',
    'right top',
    'right center',
    'right bottom',
    'center top',
    'center center',
    'center bottom',
    'initial',
    'inherit',
  ],
  'background-repeat': [
    'repeat',
    'repeat-x',
    'repeat-y',
    'no-repeat',
    'space',
    'round',
    'initial',
    'inherit',
  ],
  'background-size': ['auto', 'cover', 'contain', 'initial', 'inherit'],
  border: ['initial', 'inherit'],
  'border-bottom': ['initial', 'inherit'],
  'border-bottom-color': ['transparent', 'initial', 'inherit'],
  'border-bottom-left-radius': ['initial', 'inherit'],
  'border-bottom-right-radius': ['initial', 'inherit'],
  'border-bottom-style': [
    'none',
    'hidden',
    'dotted',
    'dashed',
    'solid',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
    'initial',
    'inherit',
  ],
  'border-bottom-width': ['medium', 'thin', 'thick', 'initial', 'inherit'],
  'border-collapse': ['separate', 'collapse', 'initial', 'inherit'],
  'border-color': ['transparent', 'initial', 'inherit'],
  'border-image': ['initial', 'inherit'],
  'border-image-outset': ['initial', 'inherit'],
  'border-image-repeat': ['stretch', 'repeat', 'round', 'space', 'initial', 'inherit'],
  'border-image-slice': ['fill', 'initial', 'inherit'],
  'border-image-source': ['none', 'image', 'initial', 'inherit'],
  'border-image-width': ['auto', 'initial', 'inherit'],
  'border-left': ['initial', 'inherit'],
  'border-left-color': ['transparent', 'initial', 'inherit'],
  'border-left-style': [
    'none',
    'hidden',
    'dotted',
    'dashed',
    'solid',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
    'initial',
    'inherit',
  ],
  'border-left-width': ['medium', 'thin', 'thick', 'initial', 'inherit'],
  'border-radius': ['initial', 'inherit'],
  'border-right': ['initial', 'inherit'],
  'border-right-color': ['transparent', 'initial', 'inherit'],
  'border-right-style': [
    'none',
    'hidden',
    'dotted',
    'dashed',
    'solid',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
    'initial',
    'inherit',
  ],
  'border-right-width': ['medium', 'thin', 'thick', 'initial', 'inherit'],
  'border-spacing': ['initial', 'inherit'],
  'border-style': [
    'none',
    'hidden',
    'dotted',
    'dashed',
    'solid',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
    'initial',
    'inherit',
  ],
  'border-top': ['initial', 'inherit'],
  'border-top-color': ['transparent', 'initial', 'inherit'],
  'border-top-left-radius': ['initial', 'inherit'],
  'border-top-right-radius': ['initial', 'inherit'],
  'border-top-style': [
    'none',
    'hidden',
    'dotted',
    'dashed',
    'solid',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
    'initial',
    'inherit',
  ],
  'border-top-width': ['medium', 'thin', 'thick', 'initial', 'inherit'],
  'border-width': ['medium', 'thin', 'thick', 'initial', 'inherit'],
  bottom: ['auto', 'initial', 'inherit'],
  'box-decoration-break': ['slice', 'clone', 'initial', 'inherit'],
  'box-shadow': ['none', 'h-offset', 'v-offset', 'blur', 'spread', 'inset', 'initial', 'inherit'],
  'box-sizing': ['content-box', 'border-box', 'initial', 'inherit'],
  'caption-side': ['top', 'bottom', 'initial', 'inherit'],
  'caret-color': ['auto'],
  '@charset': ['charset'],
  clear: ['none', 'left', 'right', 'both', 'initial', 'inherit'],
  clip: ['auto', 'shape', 'initial', 'inherit'],
  color: ['initial', 'inherit'],
  'column-count': ['auto', 'initial', 'inherit'],
  'column-fill': ['balance', 'auto', 'initial', 'inherit'],
  'column-gap': ['normal', 'initial', 'inherit'],
  'column-rule': ['initial', 'inherit'],
  'column-rule-color': ['initial', 'inherit'],
  'column-rule-style': [
    'none',
    'hidden',
    'dotted',
    'dashed',
    'solid',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
    'initial',
    'inherit',
  ],
  'column-rule-width': ['medium', 'thin', 'thick', 'initial', 'inherit'],
  'column-span': ['none', 'all', 'initial', 'inherit'],
  'column-width': ['auto', 'initial', 'inherit'],
  columns: ['auto', 'initial', 'inherit'],
  content: [
    'normal',
    'none',
    'counter',
    'attr(attribute)',
    'string',
    'open-quote',
    'close-quote',
    'no-open-quote',
    'no-close-quote',
    'url(url)',
    'initial',
    'inherit',
  ],
  'counter-increment': ['none', 'initial', 'inherit'],
  'counter-reset': ['none', 'initial', 'inherit'],
  cursor: [
    'alias',
    'all-scroll',
    'auto',
    'cell',
    'context-menu',
    'col-resize',
    'copy',
    'crosshair',
    'default',
    'e-resize',
    'ew-resize',
    'grab',
    'grabbing',
    'help',
    'move',
    'n-resize',
    'ne-resize',
    'nesw-resize',
    'ns-resize',
    'nw-resize',
    'nwse-resize',
    'no-drop',
    'none',
    'not-allowed',
    'pointer',
    'progress',
    'row-resize',
    's-resize',
    'se-resize',
    'sw-resize',
    'text',
    'URL',
    'vertical-text',
    'w-resize',
    'wait',
    'zoom-in',
    'zoom-out',
    'initial',
    'inherit',
  ],
  direction: ['ltr', 'rtl', 'initial', 'inherit'],
  display: [
    'inline',
    'block',
    'contents',
    'flex',
    'grid',
    'inline-block',
    'inline-flex',
    'inline-grid',
    'inline-table',
    'list-item',
    'run-in',
    'table',
    'table-caption',
    'table-column-group',
    'table-header-group',
    'table-footer-group',
    'table-row-group',
    'table-cell',
    'table-column',
    'table-row',
    'none',
    'initial',
    'inherit',
  ],
  'empty-cells': ['show', 'hide', 'initial', 'inherit'],
  filter: ['none', 'initial', 'inherit'],
  flex: ['auto', 'initial', 'none', 'inherit'],
  'flex-basis': ['auto', 'initial', 'inherit'],
  'flex-direction': ['row', 'row-reverse', 'column', 'column-reverse', 'initial', 'inherit'],
  'flex-flow': ['flex-direction', 'flex-wrap', 'initial', 'inherit'],
  'flex-grow': ['initial', 'inherit'],
  'flex-shrink': ['initial', 'inherit'],
  'flex-wrap': ['nowrap', 'wrap', 'wrap-reverse', 'initial', 'inherit'],
  float: ['none', 'left', 'right', 'initial', 'inherit'],
  font: [
    'caption',
    'icon',
    'menu',
    'message-box',
    'small-caption',
    'status-bar',
    'initial',
    'inherit',
  ],
  'font-family': ['initial', 'inherit'],
  'font-kerning': ['auto', 'normal', 'none'],
  'font-size': [
    'medium',
    'xx-small',
    'x-small',
    'small',
    'large',
    'x-large',
    'xx-large',
    'smaller',
    'larger',
    'initial',
    'inherit',
  ],
  'font-size-adjust': ['none', 'initial', 'inherit'],
  'font-stretch': [
    'ultra-condensed',
    'extra-condensed',
    'condensed',
    'semi-condensed',
    'normal',
    'semi-expanded',
    'expanded',
    'extra-expanded',
    'ultra-expanded',
    'initial',
    'inherit',
  ],
  'font-style': ['normal', 'italic', 'oblique', 'initial', 'inherit'],
  'font-variant': ['normal', 'small-caps', 'initial', 'inherit'],
  'font-weight': [
    'normal',
    'bold',
    'bolder',
    'lighter',
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900',
    'initial',
    'inherit',
  ],
  grid: [
    'none',
    'grid-template rows / grid-template-columns',
    'grid-template-areas',
    'grid-template rows / grid-auto-columns',
    'grid-auto-rows / grid-template-columns',
    'grid-template rows / grid-auto-flow grid-auto-columns',
    'grid-auto flow grid-auto-rows / grid-template-columns',
    'initial',
    'inherit',
  ],
  'grid-area': [],
  'grid-auto-columns': ['auto', 'max-content', 'min-content'],
  'grid-auto-flow': ['row', 'column', 'dense', 'row dense', 'column dense'],
  'grid-auto-rows': ['auto', 'max-content', 'min-content'],
  'grid-column': [],
  'grid-column-end': ['auto', 'column-line'],
  'grid-column-gap': [],
  'grid-column-start': ['auto', 'column-line'],
  'grid-gap': [],
  'grid-row': [],
  'grid-row-end': ['auto', 'column-line'],
  'grid-row-gap': [],
  'grid-row-start': ['auto', 'row-line'],
  'grid-template': [
    'none',
    'grid-template rows / grid-template-columns',
    'grid-template-areas',
    'initial',
    'inherit',
  ],
  'grid-template-areas': ['none', 'itemnames'],
  'grid-template-columns': ['none', 'auto', 'max-content', 'min-content', 'initial', 'inherit'],
  'grid-template-rows': ['none', 'auto', 'max-content', 'min-content'],
  'hanging-punctuation': ['none', 'first', 'last', 'allow-end', 'force-end', 'initial', 'inherit'],
  height: ['auto', 'initial', 'inherit', 'max-content', 'min-content', 'fit-content'],
  hyphens: ['none', 'manual', 'auto', 'initial', 'inherit'],
  isolation: ['auto', 'isolate', 'initial', 'inherit'],
  'justify-content': [
    'flex-start',
    'flex-end',
    'center',
    'space-between',
    'space-around',
    'initial',
    'inherit',
  ],
  left: ['auto', 'initial', 'inherit'],
  'letter-spacing': ['normal', 'initial', 'inherit'],
  'line-height': ['normal', 'initial', 'inherit'],
  'list-style': ['initial', 'inherit'],
  'list-style-image': ['none', 'url', 'initial', 'inherit'],
  'list-style-position': ['inside', 'outside', 'initial', 'inherit'],
  'list-style-type': [
    'disc',
    'armenian',
    'circle',
    'cjk-ideographic',
    'decimal',
    'decimal-leading-zero',
    'georgian',
    'hebrew',
    'hiragana',
    'hiragana-iroha',
    'katakana',
    'katakana-iroha',
    'lower-alpha',
    'lower-greek',
    'lower-latin',
    'lower-roman',
    'none',
    'square',
    'upper-alpha',
    'upper-greek',
    'upper-latin',
    'upper-roman',
    'initial',
    'inherit',
  ],
  margin: ['auto', 'initial', 'inherit'],
  'margin-bottom': ['auto', 'initial', 'inherit'],
  'margin-left': ['auto', 'initial', 'inherit'],
  'margin-right': ['auto', 'initial', 'inherit'],
  'margin-top': ['auto', 'initial', 'inherit'],
  'max-height': ['none', 'initial', 'inherit', 'max-content', 'min-content', 'fit-content'],
  'max-width': ['none', 'initial', 'inherit', 'max-content', 'min-content', 'fit-content'],
  'min-height': ['initial', 'inherit', 'max-content', 'min-content', 'fit-content'],
  'min-width': ['initial', 'inherit', 'max-content', 'min-content', 'fit-content'],
  'mix-blend-mode': [
    'normal',
    'multiply',
    'screen',
    'overlay',
    'darken',
    'lighten',
    'color-dodge',
    'color-burn',
    'difference',
    'exclusion',
    'hue',
    'saturation',
    'luminosity',
  ],
  'object-fit': ['fill', 'contain', 'cover', 'none', 'scale-down', 'initial', 'inherit'],
  'object-position': ['position', 'initial', 'inherit'],
  opacity: ['initial', 'inherit'],
  order: ['initial', 'inherit'],
  outline: ['initial', 'inherit'],
  'outline-color': ['invert', 'initial', 'inherit'],
  'outline-offset': ['initial', 'inherit'],
  'outline-style': [
    'none',
    'hidden',
    'dotted',
    'dashed',
    'solid',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
    'initial',
    'inherit',
  ],
  'outline-width': ['medium', 'thin', 'thick', 'initial', 'inherit'],
  overflow: ['visible', 'hidden', 'scroll', 'auto', 'initial', 'inherit'],
  'overflow-x': ['visible', 'hidden', 'scroll', 'auto', 'initial', 'inherit'],
  'overflow-y': ['visible', 'hidden', 'scroll', 'auto', 'initial', 'inherit'],
  padding: ['initial', 'inherit'],
  'padding-bottom': ['initial', 'inherit'],
  'padding-left': ['initial', 'inherit'],
  'padding-right': ['initial', 'inherit'],
  'padding-top': ['initial', 'inherit'],
  'page-break-after': ['auto', 'always', 'avoid', 'left', 'right', 'initial', 'inherit'],
  'page-break-before': ['auto', 'always', 'avoid', 'left', 'right', 'initial', 'inherit'],
  'page-break-inside': ['auto', 'avoid', 'initial', 'inherit'],
  perspective: ['none', 'initial', 'inherit'],
  'perspective-origin': ['x-axis', 'y-axis', 'initial', 'inherit'],
  'pointer-events': ['auto', 'none', 'initial', 'inherit'],
  position: ['static', 'absolute', 'fixed', 'relative', 'sticky', 'initial', 'inherit'],
  quotes: [
    'none',
    'string string string string',
    'initial',
    'inherit',
    '"',
    "'",
    '\u2039',
    '\u203a',
    '\u00ab',
    '\u00bb',
    '\u2018',
    '\u2019',
    '\u201c',
    '\u201d',
    '\u201e',
  ],
  resize: ['none', 'both', 'horizontal', 'vertical', 'initial', 'inherit'],
  right: ['auto', 'initial', 'inherit'],
  'scroll-behavior': ['auto', 'smooth', 'initial', 'inherit'],
  'tab-size': ['initial', 'inherit'],
  'table-layout': ['auto', 'fixed', 'initial', 'inherit'],
  'text-align': ['left', 'right', 'center', 'justify', 'initial', 'inherit'],
  'text-align-last': [
    'auto',
    'left',
    'right',
    'center',
    'justify',
    'start',
    'end',
    'initial',
    'inherit',
  ],
  'text-decoration': ['initial', 'inherit'],
  'text-decoration-color': ['initial', 'inherit'],
  'text-decoration-line': ['none', 'underline', 'overline', 'line-through', 'initial', 'inherit'],
  'text-decoration-style': ['solid', 'double', 'dotted', 'dashed', 'wavy', 'initial', 'inherit'],
  'text-indent': ['initial', 'inherit'],
  'text-justify': ['auto', 'inter-word', 'inter-character', 'none', 'initial', 'inherit'],
  'text-overflow': ['clip', 'ellipsis', 'string', 'initial', 'inherit'],
  'text-shadow': ['h-shadow', 'v-shadow', 'blur-radius', 'none', 'initial', 'inherit'],
  'text-transform': ['none', 'capitalize', 'uppercase', 'lowercase', 'initial', 'inherit'],
  top: ['auto', 'initial', 'inherit'],
  transform: ['none', 'initial', 'inherit'],
  'transform-origin': ['x-axis', 'y-axis', 'z-axis', 'initial', 'inherit'],
  'transform-style': ['flat', 'preserve-3d', 'initial', 'inherit'],
  transition: ['initial', 'inherit'],
  'transition-delay': ['initial', 'inherit'],
  'transition-duration': ['initial', 'inherit'],
  'transition-property': ['none', 'all', 'property', 'initial', 'inherit'],
  'transition-timing-function': [
    'ease',
    'linear',
    'ease-in',
    'ease-out',
    'ease-in-out',
    'step-start',
    'step-end',
    'initial',
    'inherit',
  ],
  'unicode-bidi': [
    'normal',
    'embed',
    'bidi-override',
    'isolate',
    'isolate-override',
    'plaintext',
    'initial',
    'inherit',
  ],
  'user-select': ['auto', 'none', 'text', 'all'],
  'vertical-align': [
    'baseline',
    'sub',
    'super',
    'top',
    'text-top',
    'middle',
    'bottom',
    'text-bottom',
    'initial',
    'inherit',
  ],
  visibility: ['visible', 'hidden', 'collapse', 'initial', 'inherit'],
  'white-space': ['normal', 'nowrap', 'pre', 'pre-line', 'pre-wrap', 'initial', 'inherit'],
  width: ['auto', 'initial', 'inherit', 'max-content', 'min-content', 'fit-content'],
  'word-break': ['normal', 'break-all', 'keep-all', 'break-word', 'initial', 'inherit'],
  'word-spacing': ['normal', 'initial', 'inherit'],
  'word-wrap': ['normal', 'break-word', 'initial', 'inherit'],
  'writing-mode': ['horizontal-tb', 'vertical-rl', 'vertical-lr'],
  'z-index': ['auto', 'initial', 'inherit'],
}
